name: Build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows manually running the action
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: "x64"
      - name: Install requirements
        run: |
          pip install poetry
          poetry install --with=build
      - name: Build with pyinstaller
        run: |
          poetry run python -m PyInstaller --onefile --noconsole -n "Captioner" "./run.py"
      - uses: actions/upload-artifact@v3
        with:
          name: Captioner-windows
          path: dist/Captioner.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: "x64"
      - name: Install requirements
        run: |
          pip install poetry
          poetry install --with=build
      - name: Build with pyinstaller
        run: |
          poetry run python -m PyInstaller --onefile --noconsole -n "Captioner" "./run.py"
      - uses: actions/upload-artifact@v3
        with:
          name: Captioner-linux
          path: dist/Captioner
